version: 2.1

job_defaults: &job_defaults
  parameters:
    python_image:
      type: string

    postgres_image:
      type: string

  environment:
    DJANGO_SQL_EXPLORER_DATABASE_URL: postgresql://postgres@localhost/postgres

  working_directory: ~/app

  docker:
    - image: <<parameters.python_image>>
    - image: <<parameters.postgres_image>>

  steps:
    - checkout
    - restore_cache:
         name: Restore pip cache
         keys:
           - django-sql-explorer-<< parameters.python_image >>-{{ checksum "requirements.txt" }}
         paths:
           - ~/cache/pip

    - run:
        name: Install dependencies
        command: python -m pip install --cache-dir ~/cache/pip --progress-bar off -r requirements.txt

    - save_cache:
        name: Save pip cache
        key: django-sql-explorer-<< parameters.python_image >>-{{ checksum "requirements.txt" }}
        paths:
          - ~/cache/pip

    - run:
        name: Run tests
        command: python manage.py test

jobs:
  build:
    <<: *job_defaults

workflows:
  version: 2

  Default build:
    jobs:
      - build:
          python_image: python:3.6.8
          postgres_image: postgres:10.5
